### ISSUE TITLE
assets files not found

### ISSUE THREAD

**Issue by mgharbik** [soycamo/jquery-nouislider-rails#5]
Hi all, I just started to use this gem but coud not load the css and js files, any suggestions?
I found a similar issue here but actually did not work to me: http://stackoverflow.com/questions/24096467/cannot-find-require-jquery-nouislider-in-application-css

Thanks

**Comment by soycamo** [comment]
This gem has been broken for a long time and I'm not sure how to fix it.

**Comment by mgharbik** [comment]
Thanks #soycamo for the feedback, we finally went for another alternative.
